# Generated by Django 4.1.1 on 2022-10-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="RegistraionNo", new_name="RegistrationNo",
        ),
    ]
